djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from leads.views import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='home-page'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/',  include('agents.urls', namespace="agents")),
    path('products/', include('products.urls', namespace='products')),
    path('accounts/', include('allauth.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    LeadListView,
    LeadDetailView,
    LeadCreateView,
    LeadUpdateView,
    LeadDeleteView,
    AssignAgentView,
    CategoryListView,
    CategoryDetailView,
    LeadCategoryUpdateView,
    CategoryCreateView,
)

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),



]

products/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    ProductListView,
    ProductCreateView,
    ProductDetailView,
    ProductUpdateView,
    ProductDeleteView,
    CategoryListView,
)

app_name = "products"

urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('create/', ProductCreateView.as_view(), name='product-create'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('<int:pk>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('<int:pk>/delete/',ProductDeleteView.as_view(), name='product-delete'),
    path('categories/', CategoryListView.as_view(), name='category-list'),

]

products/models.py
from django.db import models
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from django.utils.text import slugify


class Category(MPTTModel):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.TextField(blank=True)
    image = models.ImageField(blank=True, upload_to='images/')
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['name']    
    
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField(default=0)
    category= models.ForeignKey(Category, on_delete=models.CASCADE)
    stock = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .models import Product, Category


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'name',
            'price',
            'category',
            'stock',
        )


class PCategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            'name',
            'description',
            'image',
            'parent',
        )

products/views.py
from .models import Product, Category
from django.shortcuts import reverse 
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ProductModelForm, PCategoryModelForm
from core.mixins import OrganizorAndLoginRequiredMixin
from itertools import chain
from operator import attrgetter

class ProductListView(OrganizorAndLoginRequiredMixin, generic.ListView):
    template_name = "products/productlist.html"
    context_object_name = 'lists'

    def get_queryset(self):
        user = self.request.user
        queryset = {'products': Product.objects.all(), 
                    'category': Category.objects.all(),
        }
        return queryset


class ProductCreateView(OrganizorAndLoginRequiredMixin, generic.CreateView):
    template_name = 'products/product_create.html'
    form_class = ProductModelForm

    def get_success_url(self):
        return reverse ("products:product-list")


class ProductDetailView(OrganizorAndLoginRequiredMixin, generic.DetailView):
    template_name = "products/product_detail.html"
    context_object_name = "product"
    queryset = Product.objects.all()

class ProductUpdateView(OrganizorAndLoginRequiredMixin,generic.UpdateView):
    template_name = "products/product_update.html"
    form_class = ProductModelForm
    queryset = Product.objects.all()

    def get_success_url(self):
        return reverse ("products:product-list")


class ProductDeleteView(OrganizorAndLoginRequiredMixin,generic.DeleteView):
    template_name = "products/product_delete.html"
    form_class = ProductModelForm
    queryset = Product.objects.all()

    def get_success_url(self):
        return reverse ("products:product-list")

class CategoryListView(OrganizorAndLoginRequiredMixin, generic.ListView):
    template_name = "products/categoty_list.html"
    context_object_name = "category"
    queryset = Category.objects.all()

templates/products/category_list.html
{% extends "base.html" %}
{% load mptt_tags %}


{% block content %}
<section class="text-gray-700 body-font">
   <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
         <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
         <a href="#" class="hover:text-blue-500">Create a category</a>
      </div>

      <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
         <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
               <tr>
                  <th scope="col" class="py-3 px-6">
                     Product Category name
                  </th>
                  <th scope="col" class="py-3 px-6">
                     <div class="flex items-center">
                        Color
                        <a href="#"><svg xmlns="http://www.w3.org/2000/svg" class="ml-1 w-3 h-3" aria-hidden="true"
                              fill="currentColor" viewBox="0 0 320 512">
                              <path
                                 d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z" />
                           </svg></a>
                     </div>
                  </th>
                  <th scope="col" class="py-3 px-6">
                     <span class="sr-only">Edit</span>
                  </th>
               </tr>
            </thead>
            <tbody>
               {% recursetree category %}
                  <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                     <td scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        {{ node.name }}
                         {% if not node.is_leaf_node %}
                         <tr>
                        <td scope="row" class="py-1 px-12 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                           {{ children }}
                        </td>
                        <td class="py-4 px-6">
                        Sliver
                        </td>
                        <td class="py-4 px-6 text-right">
                           <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                        </td>
                        </tr>
                        {% endif %}
                     </td>
                     <td>S</td>
                     <td>S</td>

                     
                  </tr>
                     
               {% endrecursetree %}
            </tbody>
         </table>
      </div>
   </div>
   </section>
{% endblock content %}

templates/products/product_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-2xl mx-auto mt-10">
    <a class="hover:text-blue-500 mt-10" href="{% url 'products:product-list' %}">Go back to products</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-3xl text-gray-800">Create a new Product</h1>
    </div>
    <form method="post" action="">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>
{% endblock content %}

templates/products/product_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'products:product-list' %}">Go back to products</a>
    </div>
    <h1 class="text-3xl text-gray-800">Are you sure you want to delete this product?</h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>
</div>
{% endblock content %}

templates/products/product_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Product</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ product.name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'products:product-detail' product.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'products:product-update' product.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Update Details
                </a>    
            </div>
            <p class="leading-relaxed mb-4">{{ product.description }}</p>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Price</span>
                <span class="ml-auto text-gray-900">{{ product.price }}</span>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Quantity</span>
                <span class="ml-auto text-gray-900">{{ product.stock }}</span>
            </div>
            <div class="flex border-t  border-gray-300 py-2">
                <span class="text-gray-500">Category</span>
                <span class="ml-auto text-gray-900">{{ product.category.parent }} / {{ product.category }}</span>
            </div>
             
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/products/product_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Product</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ product.name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'products:product-detail' product.pk %}" class="flex-grow py-2 border-b-2 border-gray-300 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'products:product-update' product.pk %}" class="flex-grow  text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>    
            </div>
           <form form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'products:product-delete' product.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
             
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/products/productlist.html
{% extends "base.html" %}
{% load mptt_tags %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-3xl text-gray-800">Products</h1>
                {% if request.user.is_organizor %}
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'products:category-list' %}">
                    View Product Categories
                </a>
                {% endif %}
            </div class="mt-5">
            {% if request.user.is_organizor %}
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'products:product-create' %}">
                    Create a new Product
                </a>
            </div>
            {% endif %}
        </div>
  
        <div class="w-full">
            <form>
                <div class="flex">
                    <label for="search-dropdown" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Your
                        Email</label>
                    <button id="dropdown-button" data-dropdown-toggle="dropdown"
                        class="flex-shrink-0 w-1/5 z-10 inline-flex items-center py-2.5 px-4 text-sm font-medium text-center text-gray-900 bg-gray-100 border border-gray-300 rounded-l-lg hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-gray-700 dark:text-white dark:border-gray-600"
                        type="button">All categories <svg aria-hidden="true" class="w-4 h-4 ml-1" fill="currentColor"
                            viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                clip-rule="evenodd"></path>
                        </svg></button>
                    <div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded shadow w-44 dark:bg-gray-700"
                        data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="top"
                        style="position: absolute; inset: auto auto 0px 0px; margin: 0px; transform: translate3d(897px, 5637px, 0px);">
                        <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdown-button">
                            {% recursetree lists.category %}

                            <li>
                                <button type="button"
                                    class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"> {{ node.name }}</button>
                            </li>
                            {% endrecursetree %}
                        </ul>
                    </div>
                    <div class="relative w-full">
                        <input type="search" id="search-dropdown"
                            class="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-r-lg border-l-gray-50 border-l-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-l-gray-700  dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:border-blue-500"
                            placeholder="Search Mockups, Logos, Design Templates..." required>
                        <button type="submit"
                            class="absolute top-0 right-0 p-2.5 text-sm font-medium text-white bg-blue-700 rounded-r-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                            <svg aria-hidden="true" class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                                xmlns="http://www.w3.org/2000/svg">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                            </svg>
                            <span class="sr-only">Search</span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="flex flex-col w-full mt-3">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Product Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Status
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Price
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Stock
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Category
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                            <span class="sr-only">Edit</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in lists.products %}
                            <tr class="bg-white">
                                <td class="px-6 py-3 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <a class="text-blue-500 hover:text-blue-800" href="{% url 'products:product-detail' product.pk %}">{{ product.name }}</a>
                                </td>
                                <td class="px-6 py-3 whitespace-nowrap text-sm text-gray-500">
                                    {{ product.is_active}}
                                </td>
                                <td class="px-6 py-3 whitespace-nowrap text-sm text-gray-500">
                                    {{ product.price }}
                                </td>
                                <td class="px-6 py-3 whitespace-nowrap text-sm text-gray-500">
                                    {{ product.stock }}
                                </td>
                                <td class="px-6 py-3 whitespace-nowrap">
                                    {% if product.category %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                             {{ product.category.parent }} / {{ product.category.name }}
                                        </span>
                                    {% else %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
                                            Unassigned
                                        </span>
                                    {% endif %}
                                </td>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="{% url 'products:product-update' product.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                        Edit
                                    </a>
                                </td>
                            </tr>

                        {% empty %}

                        <p>There are currently no products</p>

                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
{% comment %}   
        {% if unassigned_leads.exists %}
            <div class="mt-5 flex flex-wrap -m-4">
                <div class="p-4 w-full">
                    <h1 class="text-4xl text-gray-800">Unassigned leads</h1>
                </div>
                {% for lead in unassigned_leads %}
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>
                        </div>
                        <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                {{ lead.first_name }} {{ lead.last_name }}
                            </h2>
                            <p class="leading-relaxed text-base">
                                {{ lead.description }}
                            </p>
                            <a href="{% url 'leads:assign-agent' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                                Assign an agent
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %} {% endcomment %}
    </div>
</section>
{% endblock content %}